version: '3.8'

services:
  foreflight-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"  # Flask UI
      - "5051:5051"  # FastAPI backend
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=src/app.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
