services:
  foreflight-dashboard:
    image: foreflight-dashboard:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.11}
        FLASK_DEBUG: 1
        FLASK_ENV: development
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "5050:5050"  # Flask UI
      - "5051:5051"  # FastAPI backend
    volumes:
      - ./src:/app/src  # Mount source code for hot reloading
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./tests:/app/tests  # Mount tests directory
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=src/app.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - BUILDKIT_PROGRESS=plain
      - DOCKER_BUILDKIT=1
    # Use tty and stdin_open for interactive debugging if needed
    tty: true
    stdin_open: true
    # Set healthcheck to ensure container is running properly
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5050/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
